export const bookingFixtures = {
  trip: {
    id: 'trip-1',
    route: {
      id: 'route-1',
      origin: 'Porto Alegre',
      destination: 'Santa Maria',
      estimatedDuration: '04:35:00',
    },
    departureAt: '2026-06-15T07:30:00-03:00',
    basePrice: 142.9,
    totalSeats: 12,
    availableSeats: 8,
  },
  tripDetail: {
    id: 'trip-1',
    route: {
      id: 'route-1',
      origin: 'Porto Alegre',
      destination: 'Santa Maria',
      estimatedDuration: '04:35:00',
    },
    departureAt: '2026-06-15T07:30:00-03:00',
    basePrice: 142.9,
    totalSeats: 12,
    availableSeats: 8,
    seats: [
      { seatNumber: 1, status: 'Available' },
      { seatNumber: 2, status: 'Occupied' },
      { seatNumber: 3, status: 'Occupied' },
      { seatNumber: 4, status: 'Available' },
      { seatNumber: 5, status: 'Available' },
      { seatNumber: 6, status: 'Available' },
      { seatNumber: 7, status: 'Available' },
      { seatNumber: 8, status: 'Available' },
    ],
  },
  reservation: {
    id: 'reservation-1',
    tripId: 'trip-1',
    seatNumber: 7,
    status: 'Active',
    code: 'ONB-12345',
    createdAt: '2026-06-01T10:00:00-03:00',
    cancelledAt: null,
    passenger: {
      id: 'passenger-1',
      fullName: 'Maria Silva',
      cpf: '12345678909',
      email: 'maria@example.com',
      birthDate: null,
    },
  },
};
